# Generated by Django 2.0.1 on 2018-04-07 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctext', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Date published')),
                ('comm', models.ForeignKey(max_length=40, on_delete='CASCADE', to='webapp.Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideas', models.OneToOneField(max_length=5, on_delete='CASCADE', to='webapp.Idea')),
                ('user', models.OneToOneField(max_length=5, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='likes',
            field=models.ForeignKey(max_length=20, on_delete='CASCADE', to='webapp.Like'),
        ),
        migrations.AddField(
            model_name='idea',
            name='user',
            field=models.OneToOneField(max_length=5, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='ideas',
            field=models.OneToOneField(max_length=5, on_delete='CASCADE', to='webapp.Idea'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.OneToOneField(max_length=5, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
