# Generated by Django 2.0.1 on 2018-04-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='comm',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='likes',
        ),
        migrations.AddField(
            model_name='idea',
            name='subject',
            field=models.CharField(default='No Subject', max_length=30),
        ),
        migrations.AlterField(
            model_name='idea',
            name='text',
            field=models.CharField(default='No text', max_length=100),
        ),
    ]
