# Generated by Django 2.0.1 on 2018-04-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180415_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='ideas',
            field=models.ForeignKey(max_length=5, on_delete='CASCADE', to='webapp.Idea'),
        ),
        migrations.AlterField(
            model_name='like',
            name='ideas',
            field=models.ForeignKey(max_length=5, on_delete='CASCADE', to='webapp.Idea'),
        ),
    ]
