# Generated by Django 2.0.1 on 2018-04-15 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180415_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(max_length=5, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
