# Generated by Django 2.0.1 on 2018-04-15 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180415_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(max_length=5, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
