# Generated by Django 2.0.1 on 2018-04-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180415_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Date published'),
        ),
    ]
