# Generated by Django 2.0.1 on 2018-04-15 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_comments_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(max_length=5, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
